const dicionario = {
  person: "pessoa",
  bicycle: "bicicleta",
  car: "carro",
  motorcycle: "motocicleta",
  airplane: "aviÃ£o",
  bus: "Ã´nibus",
  train: "trem",
  truck: "caminhÃ£o",
  boat: "barco",
  traffic_light: "semÃ¡foro",
  fire_hydrant: "hidrante",
  stop_sign: "placa de pare",
  parking_meter: "parquÃ­metro",
  bench: "banco",
  bird: "pÃ¡ssaro",
  cat: "gato",
  dog: "cachorro",
  horse: "cavalo",
  sheep: "ovelha",
  cow: "vaca",
  elephant: "elefante",
  bear: "urso",
  zebra: "zebra",
  giraffe: "girafa",
  backpack: "mochila",
  umbrella: "guarda-chuva",
  handbag: "bolsa",
  tie: "gravata",
  suitcase: "mala",
  frisbee: "frisbee",
  skis: "esquis",
  snowboard: "snowboard",
  sports_ball: "bola de esporte",
  kite: "pipa",
  baseball_bat: "taco de baseball",
  baseball_glove: "luva de baseball",
  skateboard: "skate",
  surfboard: "prancha de surf",
  tennis_racket: "raquete de tÃªnis",
  bottle: "garrafa",
  wine_glass: "taÃ§a de vinho",
  cup: "xÃ­cara",
  fork: "garfo",
  knife: "faca",
  spoon: "colher",
  bowl: "tigela",
  banana: "banana",
  apple: "maÃ§Ã£",
  sandwich: "sanduÃ­che",
  orange: "laranja",
  broccoli: "brÃ³colis",
  carrot: "cenoura",
  hot_dog: "cachorro-quente",
  pizza: "pizza",
  donut: "rosquinha",
  cake: "bolo",
  chair: "cadeira",
  couch: "sofÃ¡",
  potted_plant: "planta em vaso",
  bed: "cama",
  dining_table: "mesa de jantar",
  toilet: "vaso sanitÃ¡rio",
  tv: "televisÃ£o",
  television: "televisÃ£o",
  laptop: "notebook",
  mouse: "mouse",
  remote: "controle remoto",
  keyboard: "teclado",
  "cell phone": "celular",
  phone: "telefone",
  tablet: "tablet",
  microwave: "micro-ondas",
  oven: "forno",
  toaster: "torradeira",
  sink: "pia",
  refrigerator: "geladeira",
  book: "livro",
  clock: "relÃ³gio",
  vase: "vaso",
  scissors: "tesoura",
  teddy_bear: "urso de pelÃºcia",
  hair_drier: "secador de cabelo",
  toothbrush: "escova de dentes",
  lamp: "luminÃ¡ria",
  fan: "ventilador",
  painting: "quadro",
  carpet: "tapete",
  shelf: "prateleira",
  speaker: "caixa de som",
  stereo: "aparelho de som",
  pillow: "travesseiro",
  blanket: "cobertor",
  sheet: "lenÃ§ol",
  wardrobe: "guarda-roupa",
  dresser: "cÃ´moda",
  mirror: "espelho",
  curtain: "cortina",
  nightstand: "criado-mudo",
  alarm_clock: "despertador",
  clothes: "roupas",
  hamper: "cesto de roupa",
  rug: "tapete do quarto",
  stove: "fogÃ£o",
  blender: "liquidificador",
  coffee_maker: "cafeteira",
  dish: "prato",
  mug: "caneca",
  pan: "panela",
  pot: "caldeirÃ£o",
  kettle: "chaleira",
  tray: "bandeja",
  toothpaste: "pasta de dente",
  towel: "toalha",
  soap: "sabÃ£o",
  shampoo: "shampoo",
  shower: "chuveiro",
  razor: "barbeador",
  toilet_paper: "papel higiÃªnico",
  charger: "carregador",
  camera: "cÃ¢mera",
  headphones: "fones de ouvido",
  watch: "relÃ³gio de pulso",
  glasses: "Ã³culos",
  wallet: "carteira",
  purse: "bolsa",
  keys: "chaves",
  ball: "bola",
  broom: "vassoura",
  mop: "esfregÃ£o",
  bucket: "balde",
  box: "caixa",
  package: "pacote",
  door: "porta",
  window: "janela",
  trash_can: "lixeira",
  light: "luz",
  switch: "interruptor",
   person: "pessoa",
  chair: "cadeira",
  plant: "planta",
  control: "controle",
  outlet: "tomada"
};